FROM node:22-slim AS build
WORKDIR /app
ENV YARN_HTTP_TIMEOUT=300000
COPY package.json ./
RUN corepack enable && yarn install
COPY dist ./dist

FROM node:22-slim AS production
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package.json ./
EXPOSE 8080
CMD ["node", "dist/main"]
