server {
    listen 80;
    server_name api.ehealthwares.com;
    gzip on;
    gzip_types application/json;
    gzip_comp_level 6;

    resolver 127.0.0.11 valid=30s;
    set $backend http://rxsoft-backend:8080;

    location /identity/ { proxy_pass http://rxsoft-identity:8092/api; include /etc/nginx/proxy_params.conf; }
    location /lis/ { proxy_pass http://rxsoft-lis-backend:8091/api; include /etc/nginx/proxy_params.conf; }
    location /conversation/ { proxy_pass http://rxsoft-conversation-engine:8090/api; include /etc/nginx/proxy_params.conf; }
    location /coding/ { proxy_pass http://healthcare-interop:3000/api; include /etc/nginx/proxy_params.conf; }
    location /healthcare-concepts/ { proxy_pass http://rxsoft-healthcare-concepts:3011/api; include /etc/nginx/proxy_params.conf; }
    location / { proxy_pass $backend:8080/api/; include /etc/nginx/proxy_params.conf; }
}
