server {
    listen 80;
    server_name www.ehealthwares.com ehealthwares.com;

    location / {
        proxy_pass http://rxsoft-ehealthwares:3000;
        include /etc/nginx/proxy_params.conf;
    }
}
